/* APP */
export const NOT_FOUND = 'not-found';
export const HOME = 'home';

/* AUTH */
export const SIGN_IN = 'SignIn';

/* DATA MODELS */
export const DATA_TABLE_DETAILS = 'DataTableDetails';

/* DATA WORKFLOWS */
export const GCS_TO_GCS_RUNS_LISTING = 'GcsToGcsRuns';
export const GCS_TO_GCS_RUNS_ITEM = 'GcsToGcsRun';
export const GCS_TO_GCS_CONFIGURATIONS_LISTING = 'GcsToGcsConfs';
export const GCS_TO_GCS_CONFIGURATIONS_ITEM = 'GcsToGcsConf';

export const STORAGE_TO_STORAGE_RUNS_LISTING = 'StorageToStorageRuns';
export const STORAGE_TO_STORAGE_RUNS_ITEM = 'StorageToStorageRun';
export const STORAGE_TO_STORAGE_CONFIGURATIONS_LISTING = 'StorageToStorageConfs';
export const STORAGE_TO_STORAGE_CONFIGURATIONS_ITEM = 'StorageToStorageConf';

export const STORAGE_TO_TABLE_RUNS_LISTING = 'GcsToGbqRuns';
export const STORAGE_TO_TABLE_RUNS_ITEM = 'StorageToTableRun';
export const STORAGE_TO_TABLE_CONFIGURATIONS_LISTING = 'GcsToGbqConfs';
export const STORAGE_TO_TABLE_CONFIGURATIONS_ITEM = 'StorageToTableConf';

export const STORAGE_TO_TABLES_RUNS_LISTING = 'StorageToTablesRunsListing';
export const STORAGE_TO_TABLES_RUNS_ITEM = 'StorageToTablesRunsItem';
export const STORAGE_TO_TABLES_CONFIGURATIONS_LISTING = 'StorageToTablesConfigurationsListing';
export const STORAGE_TO_TABLES_CONFIGURATIONS_ITEM = 'StorageToTablesConfigurationsItem';

export const TABLES_TO_TABLES_RUNS_LISTING = 'TablesToTablesRuns';
export const TABLES_TO_TABLES_RUNS_ITEM = 'TablesToTablesRun';
export const TABLES_TO_TABLES_CONFIGURATIONS_LISTING = 'TablesToTablesConfs';
export const TABLES_TO_TABLES_CONFIGURATIONS_ITEM = 'TablesToTablesConf';

export const GBQ_TO_GCS_RUNS_LISTING = 'gbqToGcsRuns';
// TODO: Create run constant
export const GBQ_TO_GCS_CONFIGURATIONS_LISTING = 'gbqToGcsConfs';
export const GBQ_TO_GCS_CONFIGURATIONS_ITEM = 'GbqToGcsConf';

export const TABLE_TO_STORAGE_RUNS_LISTING = 'TableToStorageRuns';
// TODO: Create run constant
export const TABLE_TO_STORAGE_CONFIGURATIONS_LISTING = 'TableToStorageConfs';
export const TABLE_TO_STORAGE_CONFIGURATIONS_ITEM = 'TableToStorageConf';

export const VM_LAUNCHER_RUNS_LISTING = 'vmLauncherRuns';
// TODO: Create run constant
export const VM_LAUNCHER_CONFIGURATIONS_LISTING = 'vmLauncherConfs';
// TODO: Create conf constant

export const WORKFLOW_STATUS_LISTING = 'WorkflowStatus';
// TODO: Create status constant
export const WORKFLOW_CONFIGURATIONS_LISTING = 'WorkflowConfs';
// TODO: Create conf constant

/* SETTINGS */
export const PROFILE = 'userProfile';
export const USERS = 'users';
export const ACCOUNTS = 'accounts';
export const CLOUD_FUNCTIONS = 'gcpcloudfunctions';

export default {
	NOT_FOUND,
	HOME,
	SIGN_IN,
	DATA_TABLE_DETAILS,
	GCS_TO_GCS_RUNS_LISTING,
	GCS_TO_GCS_RUNS_ITEM,
	GCS_TO_GCS_CONFIGURATIONS_LISTING,
	GCS_TO_GCS_CONFIGURATIONS_ITEM,
	STORAGE_TO_STORAGE_RUNS_LISTING,
	STORAGE_TO_STORAGE_RUNS_ITEM,
	STORAGE_TO_STORAGE_CONFIGURATIONS_LISTING,
	STORAGE_TO_STORAGE_CONFIGURATIONS_ITEM,
	STORAGE_TO_TABLE_RUNS_LISTING,
	STORAGE_TO_TABLE_RUNS_ITEM,
	STORAGE_TO_TABLE_CONFIGURATIONS_LISTING,
	STORAGE_TO_TABLE_CONFIGURATIONS_ITEM,
	TABLES_TO_TABLES_RUNS_LISTING,
	TABLES_TO_TABLES_RUNS_ITEM,
	TABLES_TO_TABLES_CONFIGURATIONS_LISTING,
	TABLES_TO_TABLES_CONFIGURATIONS_ITEM,
	GBQ_TO_GCS_RUNS_LISTING,
	GBQ_TO_GCS_CONFIGURATIONS_LISTING,
	GBQ_TO_GCS_CONFIGURATIONS_ITEM,
	TABLE_TO_STORAGE_RUNS_LISTING,
	TABLE_TO_STORAGE_CONFIGURATIONS_LISTING,
	TABLE_TO_STORAGE_CONFIGURATIONS_ITEM,
	VM_LAUNCHER_RUNS_LISTING,
	VM_LAUNCHER_CONFIGURATIONS_LISTING,
	WORKFLOW_STATUS_LISTING,
	WORKFLOW_CONFIGURATIONS_LISTING,
	PROFILE,
	USERS,
	ACCOUNTS,
	CLOUD_FUNCTIONS
};
